
# server.conf 示例

# 监听 IP
server_ip=127.0.0.1
# 端口
port=8080

# LLM 配置
LLM_API_URL=https://api.moonshot.cn/v1/chat/completions
LLM_MODEL=kimi-k2.5
LLM_API_KEY=sk-xxxxxxxx

#工具和技能最多使用次数，防止死循环
MAX_TOOL_ROUNDS=25
MAX_SKILL_READ_CALLS=25



